from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import DateTime, ForeignKey, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column


class TimestampMixin:
    """
    Provides auto-managed ``created_at`` and ``updated_at`` columns.
    Both columns are timezone-aware UTC datetimes handled by the DB server.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=lambda: datetime.now(timezone.utc),
        nullable=False,
    )


class UUIDPrimaryKeyMixin:
    """
    Provides a UUID primary key generated by the Python layer (not the DB),
    ensuring IDs are known before a flush — useful for bulk inserts and
    reliable FK references before committing.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
    )


class OrganizationMixin:
    """
    Provides the ``organization_id`` foreign key for row-level multi-tenancy.

    Every core model **must** inherit from this mixin so that all queries
    can be scoped to a single tenant without cross-tenant data leakage.
    """

    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )


class BaseModelMixin(UUIDPrimaryKeyMixin, TimestampMixin):
    """
    Convenience mixin that composes UUID PK + timestamps.
    Use this for the ``Organization`` model itself (which has no org FK).
    """


class TenantModelMixin(UUIDPrimaryKeyMixin, TimestampMixin, OrganizationMixin):
    """
    Full mixin for every tenant-scoped model:
      - UUID primary key
      - created_at / updated_at timestamps
      - organization_id foreign key
    """
